# Generated by Django 4.1.2 on 2022-10-26 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_verifyphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('deadline', models.DateField()),
                ('hours', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('is_faster', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_specialist', to='user.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='order.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='TakenWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.work')),
            ],
        ),
        migrations.CreateModel(
            name='OtClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_click', to='order.work')),
            ],
        ),
        migrations.CreateModel(
            name='FileWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_works')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_work', to='order.work')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_comments', to='order.work')),
            ],
        ),
    ]
