# Generated by Django 4.1.2 on 2022-10-26 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='takenwork',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doer_work', to='order.work'),
        ),
    ]
