# Generated by Django 4.1.2 on 2022-10-29 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_otclick_user_alter_takenwork_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakenWork',
            new_name='MyTakenWork',
        ),
    ]
